In [1]:
from circuits_IC import *

## Standard general VQAs

In [2]:
# This creates the circuit

sqc = single_qubit_and_entangling(5, 2)



In [3]:
# SEe the PQC, the entangling gates will have the data later

sqc.create_PQC()

print(sqc.PQC.draw())

0
2
4
q0: ─RX─RZ─RX─o───X─RX─RZ─RX─────RX─RZ─RX─
q1: ─RX─RZ─RX─X───|─RX─RZ─RX─o───RX─RZ─RX─
q2: ─RX─RZ─RX───o─|─RX─RZ─RX─X───RX─RZ─RX─
q3: ─RX─RZ─RX───X─|─RX─RZ─RX───o─RX─RZ─RX─
q4: ─RX─RZ─RX─────o─RX─RZ─RX───X─RX─RZ─RX─


In [4]:
# SEe the QML model, the entangling gates encode data now (GPI)

sqc.create_QML()

print(sqc.QML.draw())



q0: ─RX─RZ─RX─o───────GPI─RX─RZ─RX─────────RX─RZ─RX─
q1: ─RX─RZ─RX─GPI─────|───RX─RZ─RX─o───────RX─RZ─RX─
q2: ─RX─RZ─RX─────o───|───RX─RZ─RX─GPI─────RX─RZ─RX─
q3: ─RX─RZ─RX─────GPI─|───RX─RZ─RX─────o───RX─RZ─RX─
q4: ─RX─RZ─RX─────────o───RX─RZ─RX─────GPI─RX─RZ─RX─


In [5]:
# the mapper takes parameters and data and merges them together for QML model

params = np.random.rand(len(sqc.PQC.get_parameters()))

data_params = sqc.mapper_QML(params, float(0))

print(params)
print(data_params)

[0.56932554 0.87270049 0.64121043 0.93493378 0.2622285  0.22975542
 0.20927109 0.32996516 0.65456414 0.9106003  0.39654567 0.83175246
 0.56390784 0.44497704 0.58365109 0.6266573  0.77741654 0.3910761
 0.62793659 0.91542143 0.78457411 0.30727452 0.83435092 0.16009155
 0.40072818 0.32026551 0.02941048 0.03028079 0.8304764  0.69925365
 0.64095224 0.29025041 0.42122414 0.36224055 0.20578691 0.62640723
 0.15937428 0.99419677 0.39759272 0.20425731 0.52059063 0.367673
 0.33120862 0.65151744 0.15870022]
[0.56932554 0.87270049 0.64121043 0.93493378 0.2622285  0.22975542
 0.20927109 0.32996516 0.65456414 0.9106003  0.39654567 0.83175246
 0.56390784 0.44497704 0.58365109 0.         0.         0.
 0.6266573  0.77741654 0.3910761  0.62793659 0.91542143 0.78457411
 0.30727452 0.83435092 0.16009155 0.40072818 0.32026551 0.02941048
 0.03028079 0.8304764  0.69925365 0.         0.         0.64095224
 0.29025041 0.42122414 0.36224055 0.20578691 0.62640723 0.15937428
 0.99419677 0.39759272 0.20425731 0.52

## Circuits with permutation invariance

In [6]:
sp = permutation_simple(5, 2)

sp.create_PQC()

print(sp.PQC.draw())


q0: ─RX─RX─
q1: ─RX─RX─
q2: ─RX─RX─
q3: ─RX─RX─
q4: ─RX─RX─


In [7]:
sp.create_QML()

print(sp.QML.draw())

q0:     ─RX─o────o────────X─RZ─X───────────────RX─o────o────────X─RZ─X──────── ...
q1:     ─RX─X─RZ─X────────|────|─o────o────────RX─X─RZ─X────────|────|─o────o─ ...
q2:     ─RX────────o────o─|────|─X─RZ─X────────RX────────o────o─|────|─X─RZ─X─ ...
q3:     ─RX────────X─RZ─X─|────|────────o────o─RX────────X─RZ─X─|────|──────── ...
q4:     ─RX───────────────o────o────────X─RZ─X─RX───────────────o────o──────── ...

q0: ... ───────
q1: ... ───────
q2: ... ───────
q3: ... o────o─
q4: ... X─RZ─X─


In [8]:
sp.mapper_QML(np.random.rand(2), 1)

(array([0.08347129, 0.08347129, 0.08347129, 0.08347129, 0.08347129,
        0.51654948, 0.51654948, 0.51654948, 0.51654948, 0.51654948]),
 array([0.08347129, 0.08347129, 0.08347129, 0.08347129, 0.08347129,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.51654948, 0.51654948, 0.51654948, 0.51654948, 0.51654948,
        1.        , 1.        , 1.        , 1.        , 1.        ]))

## Permutation double

In [9]:
pd = permutation_double(5, 2)

pd.create_PQC()

print(pd.PQC.draw())

q0:     ─RX─o────o────────X─RZ─X───────────────RX─o────o────────X─RZ─X──────── ...
q1:     ─RX─X─RZ─X────────|────|─o────o────────RX─X─RZ─X────────|────|─o────o─ ...
q2:     ─RX────────o────o─|────|─X─RZ─X────────RX────────o────o─|────|─X─RZ─X─ ...
q3:     ─RX────────X─RZ─X─|────|────────o────o─RX────────X─RZ─X─|────|──────── ...
q4:     ─RX───────────────o────o────────X─RZ─X─RX───────────────o────o──────── ...

q0: ... ───────
q1: ... ───────
q2: ... ───────
q3: ... o────o─
q4: ... X─RZ─X─


In [10]:
pd.create_QML()

print(pd.QML.draw())

q0:     ─RX─RX─o────o────────X─RZ─X───────────────RX─RX─o────o────────X─RZ─X── ...
q1:     ─RX─RX─X─RZ─X────────|────|─o────o────────RX─RX─X─RZ─X────────|────|─o ...
q2:     ─RX─RX────────o────o─|────|─X─RZ─X────────RX─RX────────o────o─|────|─X ...
q3:     ─RX─RX────────X─RZ─X─|────|────────o────o─RX─RX────────X─RZ─X─|────|── ...
q4:     ─RX─RX───────────────o────o────────X─RZ─X─RX─RX───────────────o────o── ...

q0: ... ─────────────
q1: ... ────o────────
q2: ... ─RZ─X────────
q3: ... ──────o────o─
q4: ... ──────X─RZ─X─


In [11]:
pd.mapper_QML(np.random.rand(4), 1)

(array([0.38362983, 0.38362983, 0.38362983, 0.38362983, 0.38362983,
        0.69006   , 0.69006   , 0.69006   , 0.69006   , 0.69006   ,
        0.64564616, 0.64564616, 0.64564616, 0.64564616, 0.64564616,
        0.90904165, 0.90904165, 0.90904165, 0.90904165, 0.90904165]),
 array([1.        , 1.        , 1.        , 1.        , 1.        ,
        0.38362983, 0.38362983, 0.38362983, 0.38362983, 0.38362983,
        0.69006   , 0.69006   , 0.69006   , 0.69006   , 0.69006   ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.64564616, 0.64564616, 0.64564616, 0.64564616, 0.64564616,
        0.90904165, 0.90904165, 0.90904165, 0.90904165, 0.90904165]))

## Permutation composed

In [12]:
pc = permutation_composed(5, 2)

pc.create_PQC()

print(pc.PQC.draw())

q0:     ─RX─o────o────────X─RZ─X───────────────RX─o────o────────X─RZ─X──────── ...
q1:     ─RX─X─RZ─X────────|────|─o────o────────RX─X─RZ─X────────|────|─o────o─ ...
q2:     ─RX────────o────o─|────|─X─RZ─X────────RX────────o────o─|────|─X─RZ─X─ ...
q3:     ─RX────────X─RZ─X─|────|────────o────o─RX────────X─RZ─X─|────|──────── ...
q4:     ─RX───────────────o────o────────X─RZ─X─RX───────────────o────o──────── ...

q0: ... ───────
q1: ... ───────
q2: ... ───────
q3: ... o────o─
q4: ... X─RZ─X─


In [13]:
pc.create_QML()

print(pc.QML.draw())

q0:     ─RY─RX─o────o────────X─RZ─X───────────────RY─RX─o────o────────X─RZ─X── ...
q1:     ─RY─RX─X─RZ─X────────|────|─o────o────────RY─RX─X─RZ─X────────|────|─o ...
q2:     ─RY─RX────────o────o─|────|─X─RZ─X────────RY─RX────────o────o─|────|─X ...
q3:     ─RY─RX────────X─RZ─X─|────|────────o────o─RY─RX────────X─RZ─X─|────|── ...
q4:     ─RY─RX───────────────o────o────────X─RZ─X─RY─RX───────────────o────o── ...

q0: ... ─────────────
q1: ... ────o────────
q2: ... ─RZ─X────────
q3: ... ──────o────o─
q4: ... ──────X─RZ─X─
